### ISSUE TITLE
An uncaught Exception was encountered Type: Error

### ISSUE THREAD

**Issue by SonamJagetia** [TealCRM/tealcrm#24]
When we log in as an admin,  the give this error on Users/dashboard page
Please help me out.. Datamapper is new for me... Is this a Datamapper problem?

An uncaught Exception was encountered
Type: Error

Message: Call to undefined method CI_DB_mysqli_driver::dm_call_method()

Filename: G:\xampp\htdocs\tealcrm\application\libraries\Datamapper.php

Line Number: 1034

**Comment by derekmajor** [comment]
It sounds like an MySQL issue to be honest.  I don't think it's a Datamapper issue but to be honest, Datamapper is extremely out dated.  There's likely some issues here and there.  Version 1.1 of TealCRM is stripping Datamapper from its codebase entirely due to the problems it can cause.  In this instance though I'd check your MySQL connection.
